### ISSUE TITLE
I got an error at build gradle and also got at map.widget.dart

### ISSUE THREAD

**Issue by SUJITH39** [SekhGulamMainuddin/Zomato-Clone#1]
1) I got an error at build gradle  like this,You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

2) I got an error at map.widget.dart at 92th line Marker is not a function and the named parameter child is required but there is no corresponding argument 

could you please resolve this error

**Comment by SekhGulamMainuddin** [comment]
Yes I'll fix it. Thanks for pointing it out.
